language: dart
dart:
  - stable
  - dev
dart_task:
  - test: --platform vm --enable-experiment=non-nullable
  - test: --platform chrome --enable-experiment=non-nullable
  - test: --platform firefox --enable-experiment=non-nullable
  - dartfmt: true
  - dartanalyzer: --fatal-infos --fatal-warnings lib test example
