name: maybe_just_nothing
version: 0.0.1
homepage: https://github.com/f3ath/maybe-just-nothing
description: Yet another variation of the Maybe monad written in Dart.
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  http: ^0.12.0
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.2
