name: maybe_just_nothing
version: 0.5.0
homepage: https://github.com/f3ath/maybe-just-nothing
description: Yet another variation of the good old Maybe monad with eager execution written in Dart.
environment:
  sdk: '>=2.12.0 <4.0.0'
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  coverage: ^1.0.1
  check_coverage: ^0.0.2


cider:
  link_template:
    tag: https://github.com/f3ath/maybe-just-nothing/releases/tag/%tag%
    diff: https://github.com/f3ath/maybe-just-nothing/compare/%from%...%to%