name: maybe_just_nothing
version: 0.4.0-nullsafety.1
homepage: https://github.com/f3ath/maybe-just-nothing
description: Yet another variation of the good old Maybe monad with eager execution written in Dart.
environment:
  sdk: '>=2.12.0-29 <3.0.0'
dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
  test_coverage: ^0.5.0

