name: maybe_just_nothing
version: 0.1.3
homepage: https://github.com/f3ath/maybe-just-nothing
description: Yet another variation of the good old Maybe monad with eager execution written in Dart. Or maybe it's just nothing.
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.2
