name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Formatter
        run: dartfmt --dry-run --set-exit-if-changed  example lib test
      - name: Analyzer
        run: dart analyze --enable-experiment=non-nullable --fatal-infos --fatal-warnings
      - name: Tests
        run: dart --enable-experiment=non-nullable test
